# This is a basic workflow to help you get started with Actions

name: Automatic Deploy of Zoe Client APP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ feature/group-categories ]
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: run npm install
        run: |
          npm install   
     
          
      - name: run tests
        run: |
          npm test
          
      - name: run build
        run: |
          npm run build
      # Runs a single command using the runners shell
      - name: Add a remote origin
        run: |
          git remote add heroku https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/${{secrets.HEROKU_APP_NAME}}.git
      # Runs a set of commands using the runners shell
      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:master -r.
